// examples/vite-solid-ts/src/index.tsx
import { render } from 'solid-js/web';
import { Bootstrap, bootstrap } from 'safetest/solid';
import * as Solid from 'solid-js';
// import { Bootstrap } from "safetest/solid";

import { TodoList as App } from './todo-list';

const root = document.getElementById('root');

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    'Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?'
  );
}

// const app = <App />;

let component: Solid.Component = () => <App />;
component = () => '';
component = () => <div></div>;

bootstrap({
  element: () => <App />,
  importGlob: import.meta.glob('./**/*.safetest.{j,t}s{,x}'),
  render: (element) => render(element, root!),
});

// render(
//   () => (
//     <Bootstrap
//       Solid={Solid}
//       // loading={''}
//       importGlob={
//         import.meta.env.DEV && import.meta.glob('./**/*.safetest.{j,t}s{,x}')
//       }
//     >
//       <App />
//     </Bootstrap>
//   ),
//   root!
// );

// examples/vite-react-ts/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';

import { bootstrap } from 'safetest/react';
// import { Bootstrap } from 'safetest/react';
import './index.css';

const root = ReactDOM.createRoot(document.getElementById('root')!);

bootstrap({
  element: (
    <React.StrictMode>
      <App />
    </React.StrictMode>
  ),
  importGlob: import.meta.glob('./**/*.safetest.{j,t}s{,x}'),
  render: (element) => root.render(element),
});
